### ISSUE TITLE
Better examples are needed on the file IDs

### ISSUE THREAD

**Issue by jmaferreira** [DLMArchivalStandardsBoard/E-ARK-AIP#10]
Example on page 27 for a file ID
> ID77146c6c-c8c3-4406-80b5-b3b41901f9d0

This example does not follow the recommendation provided earlier. It should be 
urn:uuid:77146c6c-c8c3-4406-80b5-b3b41901f9d0

**Comment by shsdev** [comment]
This is an example of a file ID (the file being part of the AIP). Only the AIP as a whole gets the identifier of the form urn:uuid:<uuid>.

**Comment by jmaferreira** [comment]
That's fine then. I might want to add a sentence to the text saying exactly that.
