### ISSUE TITLE
Sentence is difficult to understand

### ISSUE THREAD

**Issue by jmaferreira** [DLMArchivalStandardsBoard/E-ARK-AIP#12]
> When an AIP is created during ingest, it receives an unalterable identifier, which defines the AIP as one consistent logical entity. This identifier is also used to derive the name of the physical storage container.

This is so short that hardly deserves its own section. Nonetheless, what exactly does this sentence mean?! Does it mean that we should name the folder with the same name as the identifier? If so, just give that example.

**Comment by shsdev** [comment]
Addressed in v1.0.2 by extending the section.
