### ISSUE TITLE
Important diplomatic attributes are missing on the specification document (e.g. authors)

### ISSUE THREAD

**Issue by jmaferreira** [DLMArchivalStandardsBoard/E-ARK-AIP#2]
We are missing some important diplomatic attributes such as authorship of the document. 
See how PREMIS clearly identifies the authors and contributors of the document. http://www.loc.gov/standards/premis/v2/premis-2-0.pdf

This is important for reference purposes.

**Comment by delvej** [comment]
This is a generic issue

**Comment by delvej** [comment]
Janet and Karin to fix

**Comment by delvej** [comment]
See https://github.com/DLMArchivalStandardsBoard/GroupDocumentation/issues/1 for generic template issue

**Comment by delvej** [comment]
This issue is deprecated by the generic template issue
