### ISSUE TITLE
Enhance the introduction with an explanation of the purpose of the document and the AIP

### ISSUE THREAD

**Issue by jmaferreira** [DLMArchivalStandardsBoard/E-ARK-AIP#4]
In this document we fail to explain the main purpose of having a AIP format, which is to mitigate a potential preservation risk of institutional or repository meltdown and implement in a simple way a repository succession strategy. 

Repository systems are not expected to implement this AIP format, however, they are expected to be able to generate it it in a simple way for a set of AIPs.

**Comment by delvej** [comment]
See DLMArchivalStandardsBoard/GroupDocumentation#1 for generic template issue.

**Comment by shsdev** [comment]
This is the additional paragraph:
The purpose of defining a standard format for the archival information package is to pave the way for simplified repository migration. Given the increasing amount of digital content archives need to saveguard nowadays, changing the repository solution should be based on a standard exchange format. This is to say that a data repository solution provider does not necessarily have to implement this DASBOARD AIP format as the internal storage format, but it should at least allow exporting DASBOARD AIPs. By this way, the costly procedure of exporting data, producing SIPs, and ingesting them again in the new repository can be simplified. Data repository solution providers know what kind of existing data they can expect if they were chosen to replace an existing repository solution. A DASBOARD compliant repository solution should be able to immediately analyse and incorporate existing data in form of DASBOARD AIPs without the need of applying data transformation or having to fulfil varying SIP creation requirements.
