### ISSUE TITLE
Remove references to E-ARK or add a section explaining what E-ARK was

### ISSUE THREAD

**Issue by jmaferreira** [DLMArchivalStandardsBoard/E-ARK-AIP#5]
Section 2 starts with the following sentence "This AIP format specification is based on E-ARK deliverable, D4.4 “Final version of SIP-AIP conversion component”. It relates to part A of this deliverable which is the AIP format specification. "

Mentioning this without a chapter describing what E-ARK was is, in my view, pointless. This is a spec.. not a project deliverable. Context must be given.

**Comment by delvej** [comment]
See DLMArchivalStandardsBoard/GroupDocumentation#1 for generic template issue which will cover the link to E-ARK.
In addition, all references to E-ARK must then be removed.

**Comment by shsdev** [comment]
Introductory sentence added. However, the section explains the relation to other documents and explaining the relation to the original E-ARK documents therefore makes sense.
