### ISSUE TITLE
There might be a wrong enforcement in the Requirement 14 (page 16)

### ISSUE THREAD

**Issue by jmaferreira** [DLMArchivalStandardsBoard/E-ARK-AIP#7]
> Requirement 14.	The root directory of the package MUST contain a “submission” directory which is a container for the original submission and might eventually contain SIP updates which are submitted after the AIP was created. 

I might be wrong here... but shouldn’t this be a COULD? I read before that the submission folder is optional.

**Comment by shsdev** [comment]
Converted to COULD requirement.
