### ISSUE TITLE
Pointless recommendation or wrong example

### ISSUE THREAD

**Issue by jmaferreira** [DLMArchivalStandardsBoard/E-ARK-AIP#9]
> We recommended to use "as a prefix an internationally recognized standard identifier for the institution from which the SIP originates. This may lead to problems with smaller institutions, which do not have any such internationally recognized standard identifier. We propose in that case, to start the prefix with the internationally recognized standard identifier of the institution, where the AIP is created, augmented by an identifier for the institution from which the SIP originates." 

This sentence doesn’t make any sense… as right after, the example given discards the entire recommendation.

> /mets/@OBJID="urn:uuid:123e4567-e89b-12d3-a456-426655440000"  

I would remove this entire paragraph. The recommendation should be to use an international standard schema for identifiers (not institutions IDs)

**Comment by shsdev** [comment]
Paragraph removed.
